### ISSUE TITLE
Burundi - Analytic Support DHS data analysis

### ISSUE THREAD

**Issue by jb3436** [ICPI/Coordination#1]
Original Request: Please see subsequent comments for current status. 

Request submitted by Adrienne Hurst and Yesenia Saulino (SI Advisor)
Requested assistance from Noah Bartlett

**Status**: 
- Reviewed and approved by leads 3/12
- Completed 3/23

Noah gathered additional information about request. 
Noah met with Elizabeth Baldwin on Thursday 3/8 and will follow up with Julia Martin next week. Essentially they want to take The DHS prevalence results and use those to come up with revised province-level PLHIV figures to see if they match what was in the datapack. They also want those numbers compared to the MOH's DHIS-2 figures to look at coverage rates. We have a request in to USAID-B to get those figures. I will run the numbers once I have everything. 

**Background**:
Burundi Chair, Julia Martin requested additional Epi analyses - particularly of DHS data to further inform COP targets. 

**Link** to support form on sharepoint ([here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FICPI%20Engagement%2FBurundi&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence))

**Comment by jb3436** [comment]
Approved by leads 3/12 and communicated to requester.

**Comment by noahbartlett** [comment]
Revised PLHIV estimates were created using DHS data. Preliminary estimates were shared with OGAC (Julia Martin) and final estimates were shared with the country team (Apollinaire and Miriam).  A call is being scheduled between OGAC and the country team to determine next steps on how to utilize these new estimates in FY18 COP.

**Comment by jb3436** [comment]
Next steps:
- Noah @noahbartlett to forward email to and products sent to requestors
- Kashmira @neu6 to store files on Sharepoint folder
- Kashmira and Jasmine to include link to folder with final products in larger email to Burundi team. #3

**Comment by noahbartlett** [comment]
Two products were delivered and have been uploaded to SharePoint - an Excel spreadsheet which has all of the calculations in it, and a PowerPoint presentation which provided a basic step-by-step outline of what was done and the results that came out of it. @noahbartlett is scheduled to talk to Julia and the Burundi team 3/28 to officially close the loop on this. 

The takeaway messages:
1) The DHS results were not accounted for in the most recent Spectrum estimates (which formed the basis of the PLHIV estimates in the data pack). 
2) When the DHS results were included, several SNUs were affected.
      a. In the PEPFAR-covered areas, Ngozi's PLHIV numbers dramatically went down (and their coverage rate went up).
      b. Also in the PEPFAR-covered areas, Gitega's PLHIV numbers dramatically went up (and their coverage rate went down).
      c. In the non-PEPFAR-covered areas, Mwaro's coverage rate was calculated to be very low (>20%)
3) ART coverage in PEPFAR areas was calculated to be 88%; in non-PEPFAR areas 72%; and country-wide 83%. 

Final decisions on what to do with this information, vis-a-vis the COP, is still being discussed between the country team and OGAC. It is likely that PEPFAR will scale back in Ngozi and scale-up in Gitega. It is also possible that PEPFAR will try to build a presence in Mwaro.
