### ISSUE TITLE
Product Submission: OVC Dashboard

### ISSUE THREAD

**Issue by jb3436** [ICPI/Coordination#10]
**Status**
Prevention Cluster submitted the OVC dashboard to Leads for Review
Reviewers identified at leads Monday (Tola and Tom) - 5/14
Reviewers accepted and were sent dashboard - 5/15

Response Due: 5/22

**Details** 
Team uploaded v8 of the tool for leads' review. Please note that this uses dummy data and may need some adjustments based on what the actual results look like. Let us know if you have any questions. 

Tool [HERE on SharePoint ](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FClusters%2FPrevention%2FWorking%20Folder%2FOVC%2FFor%20Leads%20Review&FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D)

 Will follow up with reviewers and provide consolidated feedback by Tuesday 5/22

**Comment by jb3436** [comment]
Assigned to Tola and Tom. Communicated to the cluster and reviewers.

**Comment by shapaklyak** [comment]
fyi... OVC team are eagerly awaiting feedback :)

**Comment by hessionra** [comment]
Leads submitted feedback to Prevention Cluster Leads and OVC team on 5/23.

**Comment by shapaklyak** [comment]
@erinschelar and i are working on a response....majority of feedback addressed and taken into account. thanks!

**Comment by jb3436** [comment]
Completed
