### ISSUE TITLE
Dataset Access and Restructuring Requests

### ISSUE THREAD

**Issue by jb3436** [ICPI/Coordination#16]
Managing User Community Requests
--
Based on a conversation with systems, we discussed having a document that codified the informal relationships and set expectations about the process for dealing with requests from user communities and how the systems and ICPI teams work together to respond to those requests. 

## **Data Access and Dataset Modification Request Management Collaboration Process**

**Audience** : PEPFAR Systems teams, ICPI, Data Governance,  Agency Systems Teams, Leadership

### **Objectives:**

- To list the data user communities and highlight their unique needs for dataset structure, transformations, and suggestions.
- To provide a proposal to coordinate data access requests, calculated indicator requests, and general dataset structure transformation requests from the larger data analysis user community. This document outlines a process for streamlining and responding to request and to liaise with the teams that will fulfill the requests.  This document focuses on the ICPI/DAQ portion of this process. Recognizing that the PRIME systems and data governance tams have related mandates that are articulated in separate documents.

### **Problem Statement:**

Data analysis communities are duplicating effort in the transformation of the PEPFAR datasets (MSD, SIMS, Budget, Genie, Panorama extracts, etc.) in stats packages or through other post processing to fit into their specific analytic structural needs. In many cases indicators are calculated and datasets are restructured in order to fit into similar templates.

### **Proposal**

This group reflects a collaboration between ICPI, PRIME systems, and the data governance body. The focus on this proposal is that dataset access, data element calculations, dataset restructuring requests. These requests are received through zendesk and are routed to the DAQ and Systems team. We propose including the Data Governance team . The DAQ will review the request to determine if the request requires action on the part of the DAQ, systems team (enginerring, BI, SI, other) or the data governance team, or if the user needs orientation about where the resources currently exist.

In addition to codifying this process that already informally exists, there is a request to add more specific elements to the DATIM support dropdown that say &quot;MER/SIMS/Budget Structure Datasets&quot; which should cover access, quality issues, governance, and other types of requests.

### **Data Governance &amp; Data Systems Access and Structure Group**

The data governance group is a separate and related body. The data governance group&#39;s mandate includes what can be shared and evaluating the appropriateness of what is shared with whom. In contrast, the systems team&#39;s mandate is to ensure that stakeholders have a platform from which to get the data and that the data are in a standardized format.

See figure one for a visual of the collaboration and user communities.

 
--
![image](https://user-images.githubusercontent.com/13006198/42240315-e7ab8d74-7ed4-11e8-9fc7-f97261194c69.png)

**Comment by jb3436** [comment]
/remind me about this on July 10th at 10:00am

**Comment by jaliasd** [comment]
I'd like to understand more the problem statement. Do we have examples of when there is duplication of efforts that would be made more efficient with the proposed process? I just want to make sure we're not developing a solution in search of a problem as this is a new problem to me.

**Comment by jb3436** [comment]
@jaliasd , good question. This issue came up during IDS and I think Susan has a good sense of the actual issues and once she reveiws this she can provide more details of the problem statement. I tried my best to cobble together something cogent, but besides DOD and some CDC teams, I have not heard of this being a broad issue. 
FYI @HoustonJamie @abrahamagedewICPI @bshook

**Comment by HoustonJamie** [comment]
@jaliasd, this is my best shot at the problem statement,  Will resend the email chain from back in mid June w Karin's reply and the original request.  Not sure i understand your response @jb3436 but i guess we could discuss on Thursday. 

Specific problem: The dynamic datasets in the analytic workspaces haven't adopted many of the structural changes included in the MSDs limiting the utility of the PAWs.  A specific request that came up from the FAB to Susan after their June meeting around adding the standardized disag column which Jacob D looped to the DAQ into, but that lead to a confusing exchange between Abe/Derrick/Pilar as to what the definition of "standardized disag" was at the last analytic workspaces training.  

Broader issues: 
-How to maintain interagency access to structured datasets while handing off the day to day tasks to OGAC?
-How to formalize existing roles so that when new datastreams like expenditure get added to PDH we can communicate roles/resp to other inter agency groups and don't have to stand up a parallel processes to ensure data access again?
-How to work creation of "mock datasets" into the data calendar to reduce issues like the one around age/sex disag data at Q2? 

FYI @jb3436 @abrahamagedewICPI @bshook @kschlenker

**Comment by jb3436** [comment]
reviving this conversation 
- there have been several scenarios in the past few weeks that highlight the need for this sort of doc
- need to clarify roles/responsibilities matrix (business owner, architect, etc)
- ownership of issues at each stage that it comes in
- communications and follow through

Sent an email to @abrahamagedewICPI @kschlenker  to revise document to meet needs that more recently surfaced. 

![image](https://user-images.githubusercontent.com/13006198/43741345-0626834e-999c-11e8-8e29-764fed65ed01.png)

**Comment by jb3436** [comment]
@jaliasd we have had several meetings in the last two weeks that highlight a need to clarify a few things. @kschlenker and @abrahamagedewICPI are best positioned to revise the problem statement. They articulated some issues during senior staff yesterday that they can translate to this.

**Comment by jb3436** [comment]
Updated Visual Created by Abe @abrahamagedewICPI 

![image](https://user-images.githubusercontent.com/13006198/44350561-b0d5eb00-a46d-11e8-93a9-bd00bdb822e5.png)

**Comment by jb3436** [comment]
DAQ Notes
--
- Need to be explicit about tools vs. platform
- The gap currently is in the dataset structure - there are already processes for changes to Pano and changes to DATIM
- Several opportunities for two way interaction
- we need to be looped in earlier
- first decision point - need to have ICPI go back into the space where DAQ reviews requests initially
- have ICPI added as a CC for Zendesk and provide context 
- Transnational aspect of DAQ on Zendesk requirements  (translation of request)
- tagged on GitHub issue
- who else on the DAQ can be called upon to assist in this process so it isn't just Abe & Kristy. Need to look at LOE to determine who is available. Look for 2 or so people. Maybe Jacob. 

FYI @abrahamagedewICPI @kschlenker
