### ISSUE TITLE
Coordinator Coverage 7/19

### ISSUE THREAD

**Issue by jb3436** [ICPI/Coordination#19]
Thanks for being the on site coordinator @jaliasd . Below are a few follow up items for next week 7/23. 

Please review the coordinator’s slide Friday and present it at the inbrief Monday

**ICPI Coordinator Coverage 7/19-27**
--
**Follow Up Items**
- [x] Set up meeting with Jenny Albertini and Katie to talk through details of PMTCT request and scope out plan
- [x] Set up meeting with Katie O with the new Peds/PMTCT staff from USAID to discuss engagement (particularly the request above)
- [x] Meetings to Attend
- [x] Updated invitation: MER Datasets- Disaggregates and Age fields @ Mon Jul 23, 2018 1pm - 1:50pm (EDT) 
- [x] Pre-deployers (you will do the welcome to ICPI overview introduction slides to provide a high level perspective)
- [ ] Host Intern Day and do the welcome introduction to the event and overview of ICPI slides
- [x] Review HSS analysis  Friday and send to Vamsi from the coord office on Monday 7/23
 
**Rebecca Follow Up Items**

- [ ] Forward along the MER Refresh video alluded to in the PRIME slide during the inbrief 7/16
- [ ] Updating wiki pages for each cluster - adding their SOWs (see DIV/DAQ as examples)
- [ ] Update engagement form on sharepoint
- [ ] Update product library visual in sharepoint (move below)

Previous Coordination Coverage Notes
--
Previous notes not stored on GitHub - will start documenting them here in the future.  

FYI @hessionra @bshook @HoustonJamie

**Comment by hessionra** [comment]
@jb3436 MER Refresh Videos are still in production and/or clearance, so they have not yet been circulated. Checking with Parviez when he believes they will be ready for circulation.
