### ISSUE TITLE
Product Submission: Prevention Trend Tool

### ISSUE THREAD

**Issue by jb3436** [ICPI/Coordination#22]
Prevention Trend Tool
--
**Background**:
The Prevention Cluster has created a new Prevention Trend tool that displays quarterly and annual trends over time from FY15-FY18. This tool came from an interest by a few of our technical areas (PrEP, OVC, DREAMS) to view trend data.  Due to size limitations, our current tools only display FY17-FY18. 

**Purpose:**
The purpose of this tool is for users to update it themselves by running an R code and refreshing the backend of the tool. Although this is meant for users to update and manipulate on their own, we plan to update it on a quarterly basis with the release of clean data (4 times a year).

FYI @hessionra to add to leads agenda

Product Location [on SharePoint Here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FClusters%2FPrevention%2FWorking%20Folder%2FCross%2DCutting%2FPrevention%20Trend%20Tool&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D)
--

Status
--

- Received from prevention cluster 8/9 
- Assigned at Leads MTG Mon 8/13 to **Brittney** @bshook 
- Review Completed by Fri 8/17
- Feedback sent to cluster leads Mon 8/20

**Comment by bshook** [comment]
Sent feedback and approval to team 8/24
