### ISSUE TITLE
COOP Liaisons List

### ISSUE THREAD

**Issue by jb3436** [ICPI/Coordination#33]
ICPI Leads Approved COOP Liaison and ECT List
--
_Last updated 10/17/2018_

COOP Liaisons
--
**Tuberculosis**  -- collaborate with diagnosis cluster (report out activities on inbrief)
Co-Liaison: Catherine Nichols
Co-Liaison: TBD

**AGYW/DREAMS/OVC**  -- collaborate with prevention cluster (report out activities on inbrief)
- Co-Liaison: Kimi Sato
- Co-Liaison: Erin Schelar

**Index Testing** -- collaborate with diagnosis cluster (report out activities on inbrief)
- Co-Liaison: Shaylee Mehta
- Co-Liaison: Shazad Ahmed

**Recency Testing**  -- collaborate with diagnosis cluster (report out activities on inbrief)
- Co-Liaison: Shazad Ahmed
- Co-Liaison:  Jessica Rose 

**Viral Load** -- collaborate with diagnosis cluster (report out activities on inbrief)
- Co-Liaison: Yaa Obeng-Aduasare
- Co-Liaison:  Mackenzie Hurlston

**HIS - MOH Alignment, Data Systems….** -- collaborate with DAQ team (report out activities on inbrief)
- Co-Liaison: Anne Thomas
- Co-Liaison: Jasmine  Buttolph

**Finding Men**  -- collaborate with treatment cluster (report out activities on inbrief)
- Co-Liaison: Michelle Williams Sherlock 

CoOP Co-Leads List
--
 
**AGYW/DREAMS**
Janet Saul 
Gretchen Bachman 
Caroline Cooney Cooney
Nora Toiv Toiv
 
**Reaching Men**
Clancy Broxton (Jacqueline Devine standing in)  
Sean Cavanaugh 
Stephanie Behel 
 
**Recency Testing**
Bharat Parekh 
Andrea Kim 
Italia Rolle 
 
**Viral Load Scale-Up**
George Alemnji 
Heather Alexander 
 
**Index Testing**
Mike Grillo 
 
**Data Alignment**
Mark DeZalia 

ECT Liaisons List
--
ECT1	Yaa Obeng-Aduasare
ECT2	John (JP) Abellera & Josh Davis
ECT3	James (Jamie) Houston & Jasmine Buttolph
ECT4	Travis Lim

ECT Country Groupings
--
List of ECT Country Groupins here on GH https://github.com/ICPI/Coordination/issues/35
Liaisons Roles and Responsibilities

ECT Co-Leads List
--
**ECT1**
Mike Grillo 
Carlos Toledo 
Diana Frymus
**ECT2**
Gretchen Bachman 
George Siberry 
Stephanie Behel 
Surrbhi Modi 
**ECT3**
Trevor Rittmiller 
Peter Fonjungo
Elliot  Raizes
**ECT4**
Trista Bingham

--
![image](https://user-images.githubusercontent.com/13006198/47050608-0a594e00-d16f-11e8-9ef0-e11905445f1e.png)

SharePoint Links 
--
ICPI Management and Processes > ECT > [HERE](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FManagement%20and%20Processes%2FECT%2DCoOP%2DST3&FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D)

Emails for all POCs on SharePoint in the Word Doc version of the List

**Comment by jb3436** [comment]
Next Steps
--

- [ ] Leads confirm
- [ ] Send list and roles/responsibilities to Jeff for distribution to COOP leads
- [ ] Send best practices to liaisons
- [ ] Share on inbrief and save list on SP

**Comment by jb3436** [comment]
ECTs dissolved. Opening New list with refreshed COOP liaisons list

**Comment by HoustonJamie** [comment]
Updated in reflect new Peds COoP and ongoing support for COVID analytics (through all CoOPs and ST3)
