### ISSUE TITLE
Planning Level Letter (PLL) - MSD Comparison Analysis

### ISSUE THREAD

**Issue by jb3436** [ICPI/Coordination#46]
PLL - MSD Comparison Analysis
--
Following today’s leads meeting there was a request to support a short analytic project comparing the planning level letters to the MSD. The desire is to have a table that people can use as a reference as they get questions from their country teams about the consistency of the values in the letters. We may also use it internally to prioritize areas of support per OU.

Draft steps (these may change)
1.	Extract the data from PLL into excel (~2 hours?)
2.	Compare the data in the PLL table to MSD (~2 hours)
3.	Create summary table/slide  (30 mins)
4.	Save on SP and send to leads (5 mins)

SharePoint Folder [HERE ](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP%2019%2FPLL%20%2D%20MSD%20Analysis&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D)
--
Please store your work in this folder

**Comment by faithfawale** [comment]
My apologies, I'm just seeing this. When is this due?

**Comment by jb3436** [comment]
Mid next week - more details in an email sent Friday 1/18 - including the data needed for analysis.

**Comment by jb3436** [comment]
Issue being updated in the COP 19 Repo
