### ISSUE TITLE
Product Submission: VL Dashboard with New Changes

### ISSUE THREAD

**Issue by hessionra** [ICPI/Coordination#52]
Sent to ICPI 2/15 by @anu87 , assigned to @jaliasd and @jb3436 for Leads' Review.

VL Dashboard can be found on [SharePoint](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Clusters/HIV-TB%20Diagnosis/Working%20Folder/VL_Tool_Global_FY19Q1_021519_V3.xlsb). 

Changes include:

1. VL trends tab:
    a.	Replaced Data completeness tab
    b. Data completeness graphs converted to a table
    c. Added overall and AgeFine/Sex trends graph
2. VL Performance tab:
    a.	Moved Retention graphs to Potential Barriers tab
    b.	Combine VLC & VLS graphs
    c.	Combined Age groups graphs into one Age-Fine graph
    d.	Added site-level bubble-graph with table from ECT 2 VL tool
10. Potential Barriers tab
    a.	Moved Retention graphs here
    b.	Removed site-level tables

**Comment by jb3436** [comment]
See #7 - closing this one and will track all VL updates in ticket #7
