### ISSUE TITLE
Product Submission: New CHIPS Visuals

### ISSUE THREAD

**Issue by hessionra** [ICPI/Coordination#60]
Sent to ICPI 4/29 by @mehtasp for Leads' Review. @cnichols3h and @HoustonJamie  to review by 5/10.

VL Dashboard can be found on [SharePoint](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FClusters%2FHIV%2DTB%20Diagnosis%2FWorking%20Folder&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence). 

New visuals address the following questions:

1. How many index clients were offered index testing services?
2. How many index clients accepted index testing services?
3. How many contacts did the index client provide?
           Contacts are only sexual partners, biological children (or parent, if pediatric index client), and anyone with whom a needle was shared
5. How many contacts were tested?
6. Of the contacts tested, how many were positive?

**Comment by jb3436** [comment]
Feedback sent to Diagnosis Team

**Comment by jb3436** [comment]
Response
--
Email Subject: HTS_index mockups next steps

Team responded with acknowledgement and next steps


First of all, thanks to Jamie & Catherine for their feedback and insight, which was extremely valuable. 
The cluster co-leads, Randy and I spoke at length about next steps on the HTS_Index mockups for CHIPS based on your feedback and have come to an agreement. 
This is how we will proceed for next week’s production:

-remove the age/sex slicer altogether and remove narrative about how to interpret visuals based on age/sex slicer selection. Users will just see the entire cascade without disaggs, for now. This will somewhat align with Pano as well. 
-add arrow from 4th bar in cascade to stand alone bar to the right of cascade
-we liked Catherine/Jamie’s suggestions about analyzing the ‘index cases’ and ‘contacts provided’ sub-groups separately, but realize that we won’t be able to mock this up and get it cleared in time for next week’s tool production. We’re looking at clean Q2 for those changes at the earliest
-HTS_index indicator should maybe be revised to reflect feedback, but not sure if anyone can take this on by 5/20 

This is how we will proceed for next week’s CHIPS production and long term. Let us know if you have any qualms to this approach. We are informing the Testing SMEs of this approach as well.
