### ISSUE TITLE
Product Submission: New Visuals in KP Dashboard

### ISSUE THREAD

**Issue by hessionra** [ICPI/Coordination#64]
New visuals submitted by HSS cluster, can be found on SharePoint: https://www.pepfar.net/OGAC-HQ/icpi/Shared Documents/Clusters/HSS/Projects/KP Dash 2.0/KP_Dash_Draft_MN_May17th_TWL.xlsx. 

Kashmira and Anne assigned to review, will submit comments by COB 5/23.

Submission Email from Travis:
--
We wanted to share the most recent version of the 2.0 dashboard (not yet updated with Q2 data) with new visuals and different functionality, initially implemented by Ryan Keating.  The majority of raw data tables in the original KP dashboard are no longer.

Please consider [this version ](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Clusters/HSS/Projects/KP%20Dash%202.0/KP_Dash_Draft_MN_May17th_TWL.xlsx)the one for ICPI leads review.  We plan to update this version for Q2 next week, and would be happy to incorporate any suggestions you had prior to release.  

Jenny Hurst, Yaa, and Mala are also working on a QC guide and the actual QC which should be complete by 5/27 which is the ICPI huddle.

**Comment by hessionra** [comment]
Comments from @kkale25 
1.	Overview/Instructions tab
     a.	Remove references to FactView and replaced with MSD
     b.	Generally – update the tab to match the new visuals, etc. 
2.	KP MER Cascade Tab
     a.	Key Populations (Optional Disaggregate) Reporting (HTS_TST and TX_NEW) by Implementing Mechanism
              i.	Title is confusing – recommend rewording to be clearer
     b.	Clinical Cascade for MER indicators for Key Populations and Clinical Cascade for MER indicators for General Population / Unattributable risk
              i.	The numbers on the bar graphs should either both be oriented horizontal or vertically (I like vertically); it does look quite busy though with both the numbers and the percentages
      c.	KP_PREV & Testing Disagg complete
              i.	Should this be retitled to say “Completeness” rather than “Complete”? I’m not sure what this is showing
             ii.	Remove vertical yellow lines in bars
3.	Achievement to FY19 Target Tab
     a.	What do the red/yellow upwards arrows in the bar graphs mean? I’m guessing this is percent achievement but because the actual % number is a bit far from the arrow, it’s a little confusing. Also – would be good to add a legend of what the colors mean for those arrows mean.
     b.	% achievement is missing in a few of the bars- i.e., KP Tested, Total Tested, and a few others are missing FY17 and FY18 missing % achv 
      c.	Recommend keeping the slicers in the same place across the tabs
4.	Yield by Modality Tab
     a.	Recommend keeping the slicers in the same place across the tabs
5.	PreP Tab
     a.	Total Initiating PrEP & Percent KP 
              i.	This title is a little confusing – I see that you mean it’s total KP initiating and percent out of total that is KP right?
             ii.	Don’t forget to hid the pivot!
     b.	PrEP IMplementation by KP Group
              i.	Axis Title is missing from this graph
             ii.	Only showing FY17 data – is there a reason why?
             iii.	Spell check – “IMplementation"
6.	Self-Testing Tab
        a.	Can we make the small three bar graphs a little bigger in size on this page? KP numbers are so low it’s hard to see even after zooming in
        b.	The Pivot table here is a lot of info when viewing by all OUs. Is there a better way to build out the table? Also – is there a reason there are no FY18 targets included but FY19 targets are?
      c.	Recommend keeping the slicers in the same place across the tabs
      d.	Don’t forget to hide the grey table on the left bottom of this page
7.	Recency Tab
      a.	Coverage of Recency Tests among Key Populations
              i.	The KP numbers are so low for this bar graph – it doesn’t elucidate much information (O for FSW for all OUs and 0 for prisoners for all OUs). 
8.	Performance by Mech Tab
      a.	Please include a legend here for the conditional formatting
     b.	This pivot is huge and a bit confusing – Recommend putting into table form so it’s clear when we’re looking at targets vs. performance

**Comment by vanamala-narasimhan** [comment]
All changes made and to be re-submitted for FY19Q2 Clean Release

**Comment by jb3436** [comment]
Approved. Incorporated.
