### ISSUE TITLE
Content Review for Onboarding and Fundamentals

### ISSUE THREAD

**Issue by jb3436** [ICPI/Coordination#70]
Project Overview
--
Review educational content on SharePoint
- Orientation [on SharePoint Here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FTrainings%2FICPI%20Interagency%20Onboarding%20Training%20%28June%202019%29&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D)
- Fundamentals [on SharePoint Here](https://www.pepfar.net/Project-Pages/collab-38/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FProject%2DPages%2Fcollab%2D38%2FShared%20Documents%2FTraining%20%26%20Communications%2FPEPFAR%20Information%20Systems%20Academy%20%28PISA%29%2FFundamentals%20of%20PEPFAR%20Data%20%26%20Systems%20%2D%20PVA&FolderCTID=0x01200007E3AF9CAEC38849B68730D54E9560B6&View=%7BA8BAC8D0%2D846B%2D4EFE%2D8763%2D758855081F5D%7D)

### PRIME Systems Team SharePoint Resources
[Training and Comms Folder](https://www.pepfar.net/Project-Pages/collab-38/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FProject%2DPages%2Fcollab%2D38%2FShared%20Documents%2FTraining%20%26%20Communications&FolderCTID=0x012000C4AC9B35DC4AB84FAEEF47AE703A28CE00C799CA85D140EF45960B9C47CE99E19F&View=%7BA8BAC8D0%2D846B%2D4EFE%2D8763%2D758855081F5D%7D)
[Open EDX Folder](https://www.pepfar.net/Project-Pages/collab-38/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FProject%2DPages%2Fcollab%2D38%2FShared%20Documents%2FTraining%20%26%20Communications%2FPEPFAR%20Virtual%20Academy%20%28Open%20edX%29&FolderCTID=0x01200007E3AF9CAEC38849B68730D54E9560B6&View=%7BA8BAC8D0%2D846B%2D4EFE%2D8763%2D758855081F5D%7D)

Output:
- Recommendation on Learning Curriculum
- Identify areas to improve in communication and engagement

**Comment by ctgulley** [comment]
**Draft of Onboarding Training curriculum is attached below.**
[Onboarding Training Workplan-7.8.19.docx](https://github.com/ICPI/Coordination/files/3383393/Onboarding.Training.Workplan-7.8.19.docx)

[ICPI Course Content Analysis.xlsx](https://github.com/ICPI/Coordination/files/3383515/ICPI.Course.Content.Analysis.xlsx)

@jb3436 Could we talk through this on Thursday?

**Comment by ctgulley** [comment]
**Updated Workplan and Content Analysis attached below.**
[Onboarding Training Workplan-7.8.19.docx](https://github.com/ICPI/Coordination/files/3394134/Onboarding.Training.Workplan-7.8.19.docx)
[ICPI Course Content Analysis.xlsx](https://github.com/ICPI/Coordination/files/3394135/ICPI.Course.Content.Analysis.xlsx)

**Started PPT revisions with Module 2 - PEPFAR 101 and COP**
[Module 2 - PEPFAR 101 and COP w changes.pptx](https://github.com/ICPI/Coordination/files/3394098/Module.2.-.PEPFAR.101.and.COP.w.changes.pptx)

**Comment by ctgulley** [comment]
Updated Curriculum:
[Onboarding Training Workplan-7.8.19.docx](https://github.com/ICPI/Coordination/files/3432535/Onboarding.Training.Workplan-7.8.19.docx)

Updated Course Analysis:
[ICPI Course Content Analysis.xlsx](https://github.com/ICPI/Coordination/files/3432540/ICPI.Course.Content.Analysis.xlsx)

Updated PPTs/Modules can be found [here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FManagement%20and%20Processes%2FStaffing%2FCGulley%20Projects%2FICPI%20Onboarding%20Training%20Updated%20Slides&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence).
