### ISSUE TITLE
Transition Modules from Sharepoint to OpenEDX

### ISSUE THREAD

**Issue by ctgulley** [ICPI/Coordination#71]
Task
--
Input Sharepoint educational materials to OpenEDX platform.

Instructions on OpenEDX for Content Creators
[PVA Folder on SharePoint](https://www.pepfar.net/collab/pva/_layouts/15/start.aspx#/Documents/Forms/AllItems.aspx?RootFolder=%2Fcollab%2Fpva%2FDocuments%2FResources%20for%20Course%20Staff&FolderCTID=0x012000395A6F1EBCB7D948AF52CAADB28465D3&View=%7B47F7AADE%2DA2C1%2D4657%2D91CC%2DBD7FD4C92D8B%7D)

**Comment by jb3436** [comment]
Due 08/30 EOD: Update your ICPI Onboarding Content Materials and upload on SharePoint in this folder
Due 09/13 EOD: Add a recording to your ICPI Onboarding Content

Important notes for recording: 
•	Please add a space every 5-7 minutes of recording to do a *knowledge check*
•	Please create a short quiz at the end of your module

*Knowledge Check Instructions: Stop the recording of your module. Add a slide to indicate in your presentation that a knowledge check needs to be inserted and the continuation of the presentation will be uploaded. Type your knowledge check question on the slide. Resume recording.
