### ISSUE TITLE
Review Health Comms Resources

### ISSUE THREAD

**Issue by jb3436** [ICPI/Coordination#77]
Need to articulate "audiences" and comms strategies for different audiences and how different strategies are used for different projects. 

We can use the Open EDX project as an example of a project for which we would want to build a health comm strategy around

Resources saved in a note card here:
https://github.com/ICPI/Coordination/projects/4#card-24033729

**Comment by ctgulley** [comment]
I've come up with a high-level overall ICPI health communications strategy attached below.
[ICPI Health Communication Strategy Proposal.docx](https://github.com/ICPI/Coordination/files/3432523/ICPI.Health.Communication.Strategy.Proposal.docx)
