### ISSUE TITLE
Brownbag: MOH Alignment

### ISSUE THREAD

**Issue by jb3436** [ICPI/Coordination#83]
Attach slides
Save on SP

**Comment by hessionra** [comment]
Circulated 7/24, can be found on [SharePoint](https://www.pepfar.net/OGAC-HQ/icpi/Products/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FProducts%2FTraining%20and%20Webinars%2F2019%2FPEPFAR%5FMoH%20Data%20Alignment%20Activity%20Overview%20Brown%20Bag%2020190722&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC00C3CC873FA325DD44884DEFC36053A859&View=%7B58E3102A%2DC027%2D4C66%2DA5C7%2D84FEBE208B3C%7D).
