### ISSUE TITLE
Brownbag: DATIM analytics

### ISSUE THREAD

**Issue by jb3436** [ICPI/Coordination#84]
Attach and hyperlink to SP folder with final presentaiton

**Comment by hessionra** [comment]
[DATIM ANalytics Brown Bag 20190613.pdf](https://github.com/ICPI/Coordination/files/3437316/DATIM.ANalytics.Brown.Bag.20190613.pdf)
Attached and can be found on [SharePoint](https://www.pepfar.net/OGAC-HQ/icpi/Products/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FProducts%2FTraining%20and%20Webinars%2F2019%2FDATIM%20Analytic%20Road%20Map%20Brown%20Bag%2020190613&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC00C3CC873FA325DD44884DEFC36053A859&View=%7B58E3102A%2DC027%2D4C66%2DA5C7%2D84FEBE208B3C%7D).
